### PR TITLE
Load Config from Viper on Before hook

### LINKED ISSUE #139: NPE when passing config file via PROXY_CONFIG in single binary mode
It appears that the config can't be loaded:

```
ERR policy reva is not configured service=proxy
2020-03-12 21:23:00.592395 I | http: panic serving [::1]:51584: runtime error: invalid memory address or nil pointer dereference
goroutine 105 [running]:
net/http.(*conn).serve.func1(0xc001558320)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1767 +0x139
panic(0x55738e0, 0x6e291d0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000c87ef0, 0x5c3fce0, 0xc000162460, 0xc00033d200)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/httputil/reverseproxy.go:206 +0x144
github.com/owncloud/ocis-proxy/pkg/proxy.(*MultiHostReverseProxy).ServeHTTP(0xc000c87ef0, 0x5c3fce0, 0xc000162460, 0xc00033d200)
	/Users/mbarz/go/pkg/mod/github.com/owncloud/ocis-proxy@v0.0.0-20200310100127-5a38d286e52c/pkg/proxy/proxy.go:119 +0x37e
net/http.serverHandler.ServeHTTP(0xc0001620e0, 0x5c3fce0, 0xc000162460, 0xc00033d200)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc001558320, 0x5c49060, 0xc0014d6980)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:2927 +0x38e
```

### PR DESCRIPTION
**Pull request by refs**
## DISCLAIMERS

We need to use env variables as Viper nested config is broken. For references: https://github.com/spacemeshos/go-spacemesh/issues/245

closes https://github.com/owncloud/ocis/issues/139

/cc @micbar @IljaN @butonic

### CODE REVIEW

**Review by IljaN — APPROVED** [review]

File: pkg/command/root.go [hunk 1]
```diff
@@ -101,3 +68,47 @@ func NewLogger(cfg *config.Config) log.Logger {
 		log.Color(cfg.Log.Color),
 	)
 }
+
+// ParseConfig load configuration for every extension
+// TODO: DRY this func, take Environment Prefix as parameter, as it is the only variable
+func ParseConfig(c *cli.Context, cfg *config.Config) error {
```
Comment (butonic) [inline pkg/command/root.go:68]: Document why we need to call it in root and server?

Comment (refs) [reply pkg/command/root.go:68]: 👍

**Review by butonic — APPROVED** [review]
